### ISSUE TITLE
Small how-to for dummys

### ISSUE THREAD

**Issue by ovhelemann** [bengarvey/lineage#28]
Hi,

This looks really nice. We just had a family-conference and updated our family tree. So I would like to use it. It is my first time with coffeescript and js. I tried my best (compiling coffees into js) but did not get any result, even with the csv2json thing.

Could you please write a small tutorial how to use it? Would be so happy

thanks in advance
OVH

**Comment by bengarvey** [comment]
Yeah, working on a big revision to this since it seems people are trying to use it. Will pribably dump coffeescript completely from the repo.

**Comment by bengarvey** [comment]
@ovhelemann I realize it's like 5 years later but I shipped a Quickstart guide just for you. No coffeescript needed.   I will do a better guide at getting your own data into this, but for now that will have to do.
